### ISSUE TITLE
Make the library accessible through a Maven repository

### ISSUE THREAD

**Issue by thombergs** [yeckey/anki-drive-java#13]
The library should be accessible via Maven Central or JCenter (bintray) in order to make it usable in other projects.

**Comment by thetric** [comment]
It is possible to use any GitHub project via [JitPack.io](https://jitpack.io/#adessoAG/anki-drive-java) which can build the project just in time (hence the name). No additional configuration is necessary to publish it - just add jitpack.io as a repository

**Comment by thombergs** [comment]
Nice. Then you should create a GitHub release and provide a hint for the users to show them how to include it into their build.
